FROM wordpress:4.5-apache
MAINTAINER Philipp Wagner "philipp.wagner@incowia.com"
ENV REFRESHED_AT 2016_05_23

# see https://hub.docker.com/_/wordpress/

ENV WORDPRESS_DB_USER="cubxAdmin"
ENV WORDPRESS_PASSWORD="cubxAdmin"
ENV WORDPRESS_DB_NAME="cubbles"

VOLUME ["/var/www/html/wp-content/plugins/cubbles-runtime"]
