FROM mysql:5.7
MAINTAINER Philipp Wagner "philipp.wagner@incowia.com"
ENV REFRESHED_AT 2016_05_23

# see https://hub.docker.com/_/mysql/

ENV MYSQL_ROOT_PASSWORD="cubbles-wp-integration"
ENV MYSQL_DATABASE="cubbles"
ENV MYSQL_USER="cubxAdmin"
ENV MYSQL_PASSWORD="cubxAdmin"
